CREATE TABLE Products
(
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    ProductName NVARCHAR(50) NOT NULL,
    Price INT NOT NULL,
)

CREATE TABLE Customers
(
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    FirstName NVARCHAR(50) NOT NULL,
    LastName NVARCHAR(50) NOT NULL,
)

CREATE TABLE Orders
(
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    CustomerId UNIQUEIDENTIFIER NOT NULL,
    OrderDate DATE NOT NULL,

    FOREIGN KEY (CustomerId) REFERENCES Customers (Id) ON DELETE CASCADE
)

CREATE TABLE OrdersProducts
(
    OrderId UNIQUEIDENTIFIER NOT NULL,
    ProductId UNIQUEIDENTIFIER,
    Quantity INT NOT NULL,

    FOREIGN KEY (OrderId) REFERENCES Orders (Id) ON DELETE CASCADE,
    FOREIGN KEY (ProductId) REFERENCES Products (Id) ON DELETE SET NULL
)
